from enum import Enum


class Verdict(str, Enum):

    ACCEPTED = "ACCEPTED"

    WRONG_ANSWER = "WRONG_ANSWER"

    RUNTIME_ERROR = "RUNTIME_ERROR"

    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"

    COMPILATION_ERROR = "COMPILATION_ERROR"

    MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED"